### ISSUE TITLE
숙제 파일 실행 에러

### ISSUE THREAD

**Issue by hyunseok0222** [snu-sf-class/pp201701#4]
안녕하세요. 프원수업 수강중인 물리천문학부 오현석입니다.
숙제 파일을 다운받아서 IntelliJ에서 연 후 Test.scala 파일을 실행했더니
ClassNotFoundException 에러가 뜨는데 어떻게 해야 하나요?

Exception in thread "main" java.lang.ClassNotFoundException: Test
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)

Process finished with exit code 1

**Comment by optimisth** [comment]
IntelliJ 프로그램 창을 모두 닫고 실행할 경우

다음과 같은 화면에서 import project로 숙제파일을 열어야 해당 에러가 안나는 것 같네요.

<img width="772" alt="2017-03-20 9 15 39" src="https://cloud.githubusercontent.com/assets/17967652/24099421/850dff92-0db2-11e7-83b8-094ed28e6587.png">

**Comment by kim-yoonseung** [comment]
우선 저의 경우는 import project 중에 hw1.iml 파일을 재사용하도록 클릭했더니 문제 없이 돌아갑니다.
그래도 문제가 생긴다면, 아래를 참고하고, 그래도 안 되면 저에게 직접 질문해주세요

- import 중에 처음 hw을 다운받은 경로를 지정한 후에는 다른 경로를 지정하지 말고 그대로 next를 계속 눌러야 합니다.
- Scala SDK를 찾을 수 없다는 메시지가 창 위쪽에 노란색으로 뜨는 경우: 클릭하고 OK를 누르면 됩니다.
- File -> Project Structure -> Modules의 오른쪽 창에 "Source Folders:src"라는 문장이 없을 경우: 왼쪽 위의 - 기호를 눌러서 hw1을 삭제하고 +를 누른 후, 경로를 hw1 폴더로 수정하고 완료 클릭
- output folder 가 없다는 경우: 임의의 폴더를 생성하고 그 곳을 File -> Project Structure -> Project 의 Project compiler output의 경로로 지정 (문제가 없을 경우는 hw1\out 로 지정됨)

**Comment by hyunseok0222** [comment]
해결되었습니다. 감사합니다ㅎㅎ
